# =============================================================================
# Project Information
# =============================================================================
# Project basic info and tech stack configuration
# =============================================================================

project:
  name: ""
  description: ""
  type: ""  # web-app | api | library | cli | etc.
  initialized_at: ""

tech_stack:
  language: ""
  framework: ""
  build_tool: ""
  test_framework: ""

patterns:
  active: "ddd"
