# =============================================================================
# Requirements Summary
# =============================================================================
# Structured summary of requirements analysis results
# =============================================================================

requirements:
  summary: ""
  
features: []
  # Example:
  # - id: F1
  #   name: User authentication
  #   description: User login and registration features
  #   priority: high
  #   status: pending

actors: []
  # Example:
  # - id: A1
  #   name: Regular user
  #   description: Primary system user

business_rules: []
  # Example:
  # - id: BR1
  #   rule: User password must be at least 8 characters
  #   feature: F1
